name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - continue-on-error: True
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install Pre-Commit
      run: |
        pip install pre-commit
    - name: Run Pre-Commit
      run: |
        echo "testing pre-commit"
        pre-commit run -av
        echo "git diff the changes"
        git diff
